### ISSUE TITLE
Problem with YouTube Movies

### ISSUE THREAD

**Issue by rea987** [dvcrn/ProxMate#1]
The extension cannot open blocked YouTube Movies pages in Germany.

The video that can be unblocked by the extension in Germany:
http://www.youtube.com/watch?v=BBfYncHshJc

That video's YouTube Movies page which cannot be unblocked by the extension in Germany.
http://www.youtube.com/movie?v=BBfYncHshJc&feature=mv_sr

The video in Germany when the extension is deactivated:
http://picturf.com/i/3NU

The video in Germany when the extension is activated:
http://picturf.com/i/3NV

The video's YouTube Movies page in Germany when the extension is deactivated:
http://picturf.com/i/3NW

The video's YouTube Movies page in Germany when the extension is activated:
http://picturf.com/i/3NX

The video's YouTube Movies page in Turkey (the extension is not needed):
http://picturf.com/i/3NY

Operating System:
Ubuntu 10.10 Maverick Meerkat (32 bit)

Browser:
Firefox 11.0.0

ProxMate Version:
1.2

User Agent:
Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:11.0) Gecko/20100101 Firefox/11.0

**Comment by dvcrn** [comment]
That's because we didn't even think about youtube movies, yet.
I'll try to implement it soon, but can't promise any success tho... 

Thanks for mentioning it!

**Comment by rea987** [comment]
I am thank you for that wonderful extension. :-)

**Comment by dvcrn** [comment]
Sadly there's nothing i can do. Unblocking movie pages won't be possible. Sorry!

**Comment by rea987** [comment]
Well, actually it is not a big deal. If you check the adresses; they are really similar:

http://www.youtube.com/movie?v=BBfYncHshJc
http://www.youtube.com/watch?v=BBfYncHshJc

If you may find a way to direct blocked ...com/movie... adress to ...com/watch... page; that workaroud would be wonderful... :-)

**Comment by dvcrn** [comment]
The problem is, when you access the movie page in a blocked country, you get redirected

http://www.youtube.com/movie?v=BBfYncHshJc -> http://www.youtube.com/movies?ytsession=VGMiN8o7mUDLN3txVC0aYPwI6rVTr6WIYsSwWu5L5hJZTYjbTOluEVyVhQ3yZiuXP2vJ2Gtk5dett845aHE28DcbS4yQGARwoC7v9buBCtdtMY7-UGj40u02FsGbSOnROmuELltKsN4E5la8V_-7j1_xZVFE6kbVOycUB2Oe6cfj0aYuIMrUTlKS4AfWUvY5WuvW7O9z3ibePlqf6nWWsczeeF9b7Ia7V8HdsVBoRlAoNUQd0RBPIJ1azZlmqklZyESZR3xXG1VS9KQ7lqgWNQ

I for my part have no idea how to get the requested movie out of that ytsession link.

This is different on video pages (http://www.youtube.com/watch?v=BBfYncHshJc). You won't get redirected and therefore i know the url to the actual video

**Comment by rea987** [comment]
I see... Thanks for your effort anyway. :-)
